FROM node:14

# Create app directory
WORKDIR /home/openbackhaul/oamLog

# Install and app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

#RUN npm install
RUN npm install

# Bundle app source
COPY . .

EXPOSE 3003

#Command to start the application
CMD [ "node", "index.js" ]
